# Generated by Django 3.2.18 on 2023-06-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.login')),
            ],
        ),
        migrations.CreateModel(
            name='musicsfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='music_files')),
                ('type', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('allowed_emails', models.CharField(blank=True, max_length=200)),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musics.login')),
            ],
        ),
    ]
